/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false apps/web/cloudflare-env.d.ts` (hash: 15d37f3db19ffb6faefafbfd0c367cc5)
interface __BaseEnv_Env {
  RATE_LIMIT: KVNamespace;
  ATTACHMENTS: R2Bucket;
  DB: D1Database;
  AUTH_PEPPER: string;
  /** Optional. Without it the three email features are simply off. */
  RESEND_API_KEY?: string;
  RESEND_FROM_EMAIL?: string;
  /** Optional. Without it Turnstile is off and the limiter is the only gate. */
  TURNSTILE_SECRET_KEY?: string;
  NEXT_PUBLIC_APP_URL: string;
  RATE_LIMIT_TEST_MODE?: string;
}
declare namespace Cloudflare {
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, 'AUTH_PEPPER' | 'NEXT_PUBLIC_APP_URL'>
  > {}
}
