'use client';

import { parseGoogleMigration } from '@core/crypto';
import type { MigratedAccount } from '@core/crypto';
import { Button, Input } from '@core/ui';
import { useState } from 'react';
import { useItems } from '@/lib/client/items-store';
import { toast } from '@/lib/client/toast-store';
import { ScanQr } from './scan-qr';

/**
 * Moving one-time codes out of Google Authenticator.
 *
 * Google's "transfer accounts" screen puts every account into a QR code that is
 * not an `otpauth://` link — it is a protobuf payload, which is why pasting it
 * into the secret field does nothing useful and why this needs its own way in.
 *
 * Two things about that screen shape this. It is shown on the phone holding the
 * accounts, so most people cannot scan it with the same phone's camera — the
 * file path (a screenshot, sent to whichever device is doing the import) is the
 * normal route, not the fallback. And a large export is split across several
 * codes, so scans accumulate here instead of replacing each other.
 *
 * Nothing is saved until the list has been seen. Every one of these is a second
 * factor, and importing them silently would leave somebody unsure whether to
 * delete the originals.
 */
export function GoogleImport({ onDone }: { readonly onDone: () => void }) {
  const save = useItems((store) => store.save);

  const [found, setFound] = useState<readonly MigratedAccount[]>([]);
  const [pasted, setPasted] = useState('');
  const [error, setError] = useState('');
  const [busy, setBusy] = useState(false);

  // Counter-based codes are in the export and are not generated by this app.
  // Importing them as if they were TOTP would produce an item that shows a
  // number and never the right one.
  const usable = found.filter((account) => account.type === 'totp');
  const skipped = found.length - usable.length;

  function onScanned(value: string): void {
    const accounts = parseGoogleMigration(value);

    if (accounts.length === 0) {
      setError(
        'That code is not a Google Authenticator export. In the app: menu, then "Transfer accounts", then "Export accounts".',
      );
      return;
    }

    setError('');
    setFound((current) => {
      const seen = new Set(current.map((account) => account.secret));
      const fresh = accounts.filter((account) => !seen.has(account.secret));

      // Scanning the same code twice is the normal way to find out you are
      // holding the same code twice, so say so rather than doing nothing.
      if (fresh.length === 0) toast('Already scanned — nothing new in that code.');
      return [...current, ...fresh];
    });
  }

  async function run(): Promise<void> {
    setBusy(true);
    try {
      for (const account of usable) {
        await save({
          type: 'login',
          fields: {
            title: titleFor(account),
            ...(accountName(account) ? { username: accountName(account) } : {}),
            totpSecret: account.secret,
          },
        });
      }

      toast(`Imported ${usable.length} one-time code(s).`);
      setFound([]);

      // Back to the list, not left on an emptied form. The warning above tells
      // somebody to check a code here before deleting the originals, and they
      // cannot do that from this screen.
      onDone();
    } catch {
      setError('Something went wrong partway through. What was imported is already saved.');
    } finally {
      setBusy(false);
    }
  }

  return (
    <div className="mt-8" data-testid="google-import">
      <h3 className="typewriter mb-3 font-mono text-xs tracking-widest uppercase">
        from google authenticator
      </h3>

      <p className="text-muted mb-4 font-mono text-xs leading-relaxed">
        <span aria-hidden="true">&gt; </span>
        In Google Authenticator: menu, <span className="text-fg">Transfer accounts</span>,{' '}
        <span className="text-fg">Export accounts</span>. Scan the code it shows, or screenshot it
        and choose the image here. A long list becomes several codes — scan each one.
      </p>

      <ScanQr onScanned={onScanned} label="scan the export code" />

      {/*
        The way in when scanning is not available at all, which is most desktop
        browsers. Without it this screen was a dead end on any machine that
        could not decode: the item form has always taken a pasted `otpauth://`
        link, but Google's export is a different scheme and had nowhere to go.

        The realistic route is still a phone — Chrome on Android decodes, so
        opening Core there and scanning is fewer steps than extracting this
        text. Said below rather than left to be worked out.
      */}
      <form
        className="mt-4 flex flex-wrap items-center gap-3"
        onSubmit={(event) => {
          event.preventDefault();
          onScanned(pasted.trim());
          setPasted('');
        }}
      >
        <Input
          value={pasted}
          onChange={(event) => setPasted(event.target.value)}
          placeholder="otpauth-migration://offline?data=..."
          aria-label="paste the export link"
          autoComplete="off"
          spellCheck={false}
          className="min-w-0 flex-1"
          data-testid="google-paste"
        />
        <Button type="submit" disabled={pasted.trim() === ''} data-testid="google-paste-read">
          read it
        </Button>
      </form>

      <p className="text-muted mt-3 font-mono text-xs leading-relaxed">
        <span aria-hidden="true">&gt; </span>
        If this browser cannot scan, open Core on an Android phone and scan there — the codes land
        in the same vault. Pasting the <code>otpauth-migration://</code> link works too, if you have
        a way to read one.
      </p>

      {error !== '' ? (
        <p role="alert" className="text-danger mt-4 font-mono text-xs" data-testid="google-error">
          <span aria-hidden="true">! </span>
          {error}
        </p>
      ) : null}

      {found.length > 0 ? (
        <div className="mt-6">
          <p className="text-muted font-mono text-xs" data-testid="google-summary">
            <span aria-hidden="true">&gt; </span>
            {usable.length} code(s) to import
            {skipped > 0 ? `; ${skipped} counter-based one(s) this app cannot generate` : ''}.
          </p>

          <ul className="border-line mt-3 border font-mono text-xs" data-testid="google-preview">
            {found.map((account) => (
              <li
                key={account.secret}
                className="border-line flex flex-wrap gap-x-3 border-b p-3 last:border-b-0"
              >
                <span className="text-fg">{titleFor(account)}</span>
                <span className="text-muted">{accountName(account)}</span>
                {account.type === 'hotp' ? (
                  <span className="text-warning ml-auto">counter-based, skipped</span>
                ) : null}
              </li>
            ))}
          </ul>

          <div className="mt-4 flex flex-wrap gap-3">
            <Button
              onClick={() => void run()}
              disabled={busy || usable.length === 0}
              data-testid="google-run"
            >
              {busy ? 'importing...' : `import ${usable.length}`}
            </Button>
            <Button variant="ghost" onClick={() => setFound([])} data-testid="google-clear">
              start over
            </Button>
          </div>

          <p className="text-warning mt-4 font-mono text-xs">
            <span aria-hidden="true">! </span>
            Keep the accounts in Google Authenticator until you have seen a code here match. An
            export is a copy, not a move.
          </p>
        </div>
      ) : null}
    </div>
  );
}

/**
 * Google writes the label as `Issuer:account`, and sometimes only the account.
 * The issuer field is separate and is the better title when it is there.
 */
function titleFor(account: MigratedAccount): string {
  if (account.issuer !== '') return account.issuer;

  const colon = account.name.indexOf(':');
  const prefix = colon > 0 ? account.name.slice(0, colon) : '';
  return prefix !== '' ? prefix : account.name || 'one-time code';
}

function accountName(account: MigratedAccount): string {
  const colon = account.name.indexOf(':');
  return (colon > 0 ? account.name.slice(colon + 1) : account.name).trim();
}
